using System.Text.Encodings.Web;
using System.Text.Json;
using HasamiBoard.Models;

namespace HasamiBoard.Services;

/// <summary>HTTP / POSIX errno.h / Windows / SMTP の各エラーコード一覧を保持する静的データテーブルと検索ロジック。外部通信は行わずアプリ内蔵データのみで完結する。</summary>
public static class ErrorCodeService
{
    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        WriteIndented = true,
        Encoder = JavaScriptEncoder.UnsafeRelaxedJsonEscaping,
    };

    public static IReadOnlyList<ErrorCodeEntry> HttpStatusCodes { get; } = new List<ErrorCodeEntry>
    {
        new("100", null, "Continue", "続行"),
        new("101", null, "Switching Protocols", "プロトコルの切り替え"),
        new("102", null, "Processing (WebDAV)", "処理中 (WebDAV)"),
        new("103", null, "Early Hints", "早期ヒント"),
        new("200", null, "OK", "成功"),
        new("201", null, "Created", "作成完了"),
        new("202", null, "Accepted", "受理済み (処理は未完了)"),
        new("203", null, "Non-Authoritative Information", "非公式情報"),
        new("204", null, "No Content", "コンテンツなし"),
        new("205", null, "Reset Content", "コンテンツのリセット"),
        new("206", null, "Partial Content", "部分的コンテンツ"),
        new("207", null, "Multi-Status (WebDAV)", "マルチステータス (WebDAV)"),
        new("208", null, "Already Reported (WebDAV)", "既に報告済み (WebDAV)"),
        new("226", null, "IM Used", "IM使用済み"),
        new("300", null, "Multiple Choices", "複数の選択肢"),
        new("301", null, "Moved Permanently", "恒久的に移動しました"),
        new("302", null, "Found (Previously \"Moved Temporarily\")", "発見 (一時的に移動)"),
        new("303", null, "See Other", "他を参照"),
        new("304", null, "Not Modified", "未更新"),
        new("305", null, "Use Proxy (Deprecated)", "プロキシを使用してください (非推奨)"),
        new("307", null, "Temporary Redirect", "一時的リダイレクト"),
        new("308", null, "Permanent Redirect", "恒久的リダイレクト"),
        new("400", null, "Bad Request", "不正なリクエスト"),
        new("401", null, "Unauthorized", "認証が必要です"),
        new("402", null, "Payment Required", "支払いが必要です"),
        new("403", null, "Forbidden", "禁止されています"),
        new("404", null, "Not Found", "見つかりません"),
        new("405", null, "Method Not Allowed", "許可されていないメソッドです"),
        new("406", null, "Not Acceptable", "受理できません"),
        new("407", null, "Proxy Authentication Required", "プロキシ認証が必要です"),
        new("408", null, "Request Timeout", "リクエストタイムアウト"),
        new("409", null, "Conflict", "競合が発生しました"),
        new("410", null, "Gone", "リソースは消失しました"),
        new("411", null, "Length Required", "Content-Lengthの指定が必要です"),
        new("412", null, "Precondition Failed", "前提条件が満たされませんでした"),
        new("413", null, "Payload Too Large", "リクエストのペイロードが大きすぎます"),
        new("414", null, "URI Too Long", "URIが長すぎます"),
        new("415", null, "Unsupported Media Type", "サポートされていないメディアタイプです"),
        new("416", null, "Range Not Satisfiable", "要求された範囲を満たせません"),
        new("417", null, "Expectation Failed", "Expectヘッダーの内容を満たせませんでした"),
        new("418", null, "I'm a teapot", "私はティーポットです (ジョークRFC)"),
        new("421", null, "Misdirected Request", "誤った宛先へのリクエストです"),
        new("422", null, "Unprocessable Entity", "処理できないエンティティです"),
        new("423", null, "Locked (WebDAV)", "ロックされています (WebDAV)"),
        new("424", null, "Failed Dependency (WebDAV)", "依存関係の処理に失敗しました (WebDAV)"),
        new("425", null, "Too Early", "リクエストが早すぎます"),
        new("426", null, "Upgrade Required", "プロトコルのアップグレードが必要です"),
        new("428", null, "Precondition Required", "前提条件の指定が必要です"),
        new("429", null, "Too Many Requests", "リクエストが多すぎます"),
        new("431", null, "Request Header Fields Too Large", "リクエストヘッダーが大きすぎます"),
        new("451", null, "Unavailable For Legal Reasons", "法的理由により利用できません"),
        new("500", null, "Internal Server Error", "サーバー内部エラー"),
        new("501", null, "Not Implemented", "実装されていません"),
        new("502", null, "Bad Gateway", "不正なゲートウェイです"),
        new("503", null, "Service Unavailable", "サービスが利用できません"),
        new("504", null, "Gateway Timeout", "ゲートウェイタイムアウト"),
        new("505", null, "HTTP Version Not Supported", "サポートされていないHTTPバージョンです"),
        new("506", null, "Variant Also Negotiates", "バリアントも交渉されます"),
        new("507", null, "Insufficient Storage (WebDAV)", "記憶域が不足しています (WebDAV)"),
        new("508", null, "Loop Detected (WebDAV)", "ループを検出しました (WebDAV)"),
        new("510", null, "Not Extended", "拡張が必要です"),
        new("511", null, "Network Authentication Required", "ネットワーク認証が必要です"),
    };

    public static IReadOnlyList<ErrorCodeEntry> ErrnoCodes { get; } = new List<ErrorCodeEntry>
    {
        new("1", "EPERM", "Operation not permitted", "操作が許可されていません"),
        new("2", "ENOENT", "No such file or directory", "そのようなファイルやディレクトリはありません"),
        new("3", "ESRCH", "No such process", "そのようなプロセスはありません"),
        new("4", "EINTR", "Interrupted function call", "関数呼び出しが割り込まれました"),
        new("5", "EIO", "Input/output error", "入出力エラー"),
        new("6", "ENXIO", "No such device or address", "そのようなデバイスやアドレスはありません"),
        new("7", "E2BIG", "Argument list too long", "引数リストが長すぎます"),
        new("8", "ENOEXEC", "Exec format error", "実行形式エラー"),
        new("9", "EBADF", "Bad file descriptor", "不正なファイルディスクリプタです"),
        new("10", "ECHILD", "No child processes", "子プロセスがありません"),
        new("11", "EAGAIN", "Resource temporarily unavailable (same value as EWOULDBLOCK)", "リソースが一時的に利用できません (EWOULDBLOCKと同値)"),
        new("11", "EWOULDBLOCK", "Operation would block (same value as EAGAIN)", "操作がブロックされます (EAGAINと同値)"),
        new("12", "ENOMEM", "Not enough space (cannot allocate memory)", "メモリを割り当てられません"),
        new("13", "EACCES", "Permission denied", "アクセスが拒否されました"),
        new("14", "EFAULT", "Bad address", "不正なアドレスです"),
        new("16", "EBUSY", "Device or resource busy", "デバイスまたはリソースがビジー状態です"),
        new("17", "EEXIST", "File exists", "ファイルは既に存在します"),
        new("18", "EXDEV", "Improper link (cross-device link)", "不適切なリンクです (デバイスをまたぐリンク)"),
        new("19", "ENODEV", "No such device", "そのようなデバイスはありません"),
        new("20", "ENOTDIR", "Not a directory", "ディレクトリではありません"),
        new("21", "EISDIR", "Is a directory", "ディレクトリです"),
        new("22", "EINVAL", "Invalid argument", "不正な引数です"),
        new("23", "ENFILE", "Too many open files in system", "システム全体でオープンファイルが多すぎます"),
        new("24", "EMFILE", "Too many open files", "オープンファイルが多すぎます"),
        new("25", "ENOTTY", "Inappropriate I/O control operation", "不適切なI/O制御操作です"),
        new("26", "ETXTBSY", "Text file busy", "テキストファイルがビジー状態です"),
        new("27", "EFBIG", "File too large", "ファイルが大きすぎます"),
        new("28", "ENOSPC", "No space left on device", "デバイスに空き容量がありません"),
        new("29", "ESPIPE", "Invalid seek", "不正なシーク操作です"),
        new("30", "EROFS", "Read-only file system", "読み取り専用ファイルシステムです"),
        new("31", "EMLINK", "Too many links", "リンクが多すぎます"),
        new("32", "EPIPE", "Broken pipe", "パイプが壊れています"),
        new("33", "EDOM", "Mathematics argument out of domain of function", "数学関数の引数が定義域外です"),
        new("34", "ERANGE", "Result too large (out of range)", "結果が範囲外です"),
        new("35", "EDEADLK", "Resource deadlock would occur", "リソースのデッドロックが発生します"),
        new("36", "ENAMETOOLONG", "Filename too long", "ファイル名が長すぎます"),
        new("37", "ENOLCK", "No locks available", "利用可能なロックがありません"),
        new("38", "ENOSYS", "Function not implemented", "関数が実装されていません"),
        new("39", "ENOTEMPTY", "Directory not empty", "ディレクトリが空ではありません"),
        new("40", "ELOOP", "Too many levels of symbolic links", "シンボリックリンクの階層が多すぎます"),
        new("42", "ENOMSG", "No message of desired type", "要求された型のメッセージがありません"),
        new("43", "EIDRM", "Identifier removed", "識別子が削除されました"),
        new("60", "ENOSTR", "Not a STREAM", "STREAMではありません"),
        new("61", "ENODATA", "No message is available", "利用可能なメッセージがありません"),
        new("62", "ETIME", "STREAM ioctl timeout", "STREAM ioctlタイムアウト"),
        new("63", "ENOSR", "No STREAM resources", "STREAMリソースがありません"),
        new("67", "ENOLINK", "Link has been severed", "リンクが切断されました"),
        new("71", "EPROTO", "Protocol error", "プロトコルエラー"),
        new("72", "EMULTIHOP", "Multihop attempted", "マルチホップが試行されました"),
        new("74", "EBADMSG", "Bad message", "不正なメッセージです"),
        new("75", "EOVERFLOW", "Value too large to be stored in data type", "値がデータ型に格納するには大きすぎます"),
        new("84", "EILSEQ", "Illegal byte sequence", "不正なバイトシーケンスです"),
        new("88", "ENOTSOCK", "Not a socket", "ソケットではありません"),
        new("89", "EDESTADDRREQ", "Destination address required", "宛先アドレスが必要です"),
        new("90", "EMSGSIZE", "Message too large", "メッセージが大きすぎます"),
        new("91", "EPROTOTYPE", "Protocol wrong type for socket", "ソケットに対してプロトコルの種類が間違っています"),
        new("92", "ENOPROTOOPT", "Protocol not available", "プロトコルオプションが利用できません"),
        new("93", "EPROTONOSUPPORT", "Protocol not supported", "プロトコルがサポートされていません"),
        new("95", "EOPNOTSUPP", "Operation not supported on socket (same value as ENOTSUP)", "ソケットでサポートされていない操作です (ENOTSUPと同値)"),
        new("95", "ENOTSUP", "Not supported (same value as EOPNOTSUPP)", "サポートされていません (EOPNOTSUPPと同値)"),
        new("97", "EAFNOSUPPORT", "Address family not supported", "アドレスファミリがサポートされていません"),
        new("98", "EADDRINUSE", "Address already in use", "アドレスは既に使用されています"),
        new("99", "EADDRNOTAVAIL", "Address not available", "アドレスが利用できません"),
        new("100", "ENETDOWN", "Network is down", "ネットワークがダウンしています"),
        new("101", "ENETUNREACH", "Network unreachable", "ネットワークに到達できません"),
        new("102", "ENETRESET", "Connection aborted by network", "ネットワークによって接続が中断されました"),
        new("103", "ECONNABORTED", "Connection aborted", "接続が中断されました"),
        new("104", "ECONNRESET", "Connection reset", "接続がリセットされました"),
        new("105", "ENOBUFS", "No buffer space available", "利用可能なバッファ領域がありません"),
        new("106", "EISCONN", "Socket is connected", "ソケットは接続済みです"),
        new("107", "ENOTCONN", "Socket is not connected", "ソケットが接続されていません"),
        new("110", "ETIMEDOUT", "Connection timed out", "接続がタイムアウトしました"),
        new("111", "ECONNREFUSED", "Connection refused", "接続が拒否されました"),
        new("113", "EHOSTUNREACH", "Host is unreachable", "ホストに到達できません"),
        new("114", "EALREADY", "Connection already in progress", "接続は既に処理中です"),
        new("115", "EINPROGRESS", "Operation in progress", "操作は処理中です"),
        new("116", "ESTALE", "Stale file handle", "古いファイルハンドルです"),
        new("122", "EDQUOT", "Disk quota exceeded", "ディスククォータを超過しました"),
        new("125", "ECANCELED", "Operation canceled", "操作がキャンセルされました"),
        new("130", "EOWNERDEAD", "Previous owner died (robust mutex)", "以前の所有者が終了しました (ロバストミューテックス)"),
        new("131", "ENOTRECOVERABLE", "State not recoverable", "状態を回復できません"),
    };

    public static IReadOnlyList<ErrorCodeEntry> WindowsErrorCodes { get; } = new List<ErrorCodeEntry>
    {
        new("0", "ERROR_SUCCESS", "The operation completed successfully.", "操作は正常に完了しました。"),
        new("1", "ERROR_INVALID_FUNCTION", "Incorrect function.", "関数が正しくありません。"),
        new("2", "ERROR_FILE_NOT_FOUND", "The system cannot find the file specified.", "指定されたファイルが見つかりません。"),
        new("3", "ERROR_PATH_NOT_FOUND", "The system cannot find the path specified.", "指定されたパスが見つかりません。"),
        new("4", "ERROR_TOO_MANY_OPEN_FILES", "The system cannot open the file.", "オープンできるファイルの数が多すぎます。"),
        new("5", "ERROR_ACCESS_DENIED", "Access is denied.", "アクセスが拒否されました。"),
        new("6", "ERROR_INVALID_HANDLE", "The handle is invalid.", "ハンドルが無効です。"),
        new("8", "ERROR_NOT_ENOUGH_MEMORY", "Not enough storage is available to process this command.", "このコマンドを処理するのに十分な記憶域がありません。"),
        new("9", "ERROR_INVALID_BLOCK", "The storage control block address is invalid.", "記憶域制御ブロックのアドレスが無効です。"),
        new("11", "ERROR_BAD_FORMAT", "An attempt was made to load a program with an incorrect format.", "形式が正しくないプログラムを読み込もうとしました。"),
        new("12", "ERROR_INVALID_ACCESS", "The access code is invalid.", "アクセスコードが無効です。"),
        new("13", "ERROR_INVALID_DATA", "The data is invalid.", "データが無効です。"),
        new("14", "ERROR_OUTOFMEMORY", "Not enough storage is available to complete this operation.", "この操作を完了するのに十分な記憶域がありません。"),
        new("15", "ERROR_INVALID_DRIVE", "The system cannot find the drive specified.", "指定されたドライブが見つかりません。"),
        new("16", "ERROR_CURRENT_DIRECTORY", "The directory cannot be removed.", "カレントディレクトリを削除できません。"),
        new("17", "ERROR_NOT_SAME_DEVICE", "The system cannot move the file to a different disk drive.", "別のディスクドライブへファイルを移動できません。"),
        new("18", "ERROR_NO_MORE_FILES", "There are no more files.", "これ以上ファイルはありません。"),
        new("19", "ERROR_WRITE_PROTECT", "The media is write protected.", "メディアが書き込み禁止になっています。"),
        new("20", "ERROR_BAD_UNIT", "The system cannot find the device specified.", "指定されたデバイスが見つかりません。"),
        new("21", "ERROR_NOT_READY", "The device is not ready.", "デバイスの準備ができていません。"),
        new("22", "ERROR_BAD_COMMAND", "The device does not recognize the command.", "デバイスがコマンドを認識しません。"),
        new("23", "ERROR_CRC", "Data error (cyclic redundancy check).", "データエラーです (巡回冗長検査)。"),
        new("26", "ERROR_SEEK", "The drive cannot locate a specific area or track on the disk.", "ドライブがディスク上の特定の領域やトラックを見つけられません。"),
        new("29", "ERROR_WRITE_FAULT", "The system cannot write to the specified device.", "指定されたデバイスに書き込めません。"),
        new("30", "ERROR_READ_FAULT", "The system cannot read from the specified device.", "指定されたデバイスから読み取れません。"),
        new("31", "ERROR_GEN_FAILURE", "A device attached to the system is not functioning.", "システムに接続されたデバイスが機能していません。"),
        new("32", "ERROR_SHARING_VIOLATION", "The process cannot access the file because it is being used by another process.", "別のプロセスが使用しているため、ファイルにアクセスできません。"),
        new("33", "ERROR_LOCK_VIOLATION", "The process cannot access the file because another process has locked a portion of the file.", "別のプロセスがファイルの一部をロックしているため、アクセスできません。"),
        new("34", "ERROR_WRONG_DISK", "The wrong diskette is in the drive.", "ドライブに正しくないディスケットが入っています。"),
        new("38", "ERROR_HANDLE_EOF", "Reached the end of the file.", "ファイルの終端に達しました。"),
        new("39", "ERROR_HANDLE_DISK_FULL", "The disk is full.", "ディスクがいっぱいです。"),
        new("50", "ERROR_NOT_SUPPORTED", "The network request is not supported.", "ネットワーク要求はサポートされていません。"),
        new("53", "ERROR_BAD_NETPATH", "The network path was not found.", "ネットワークパスが見つかりません。"),
        new("54", "ERROR_NETWORK_BUSY", "The network is busy.", "ネットワークがビジー状態です。"),
        new("55", "ERROR_DEV_NOT_EXIST", "The specified network resource or device is no longer available.", "指定されたネットワークリソースまたはデバイスは使用できません。"),
        new("64", "ERROR_NETNAME_DELETED", "The specified network name is no longer available.", "指定されたネットワーク名は使用できません。"),
        new("65", "ERROR_NETWORK_ACCESS_DENIED", "Network access is denied.", "ネットワークへのアクセスが拒否されました。"),
        new("67", "ERROR_BAD_NET_NAME", "The network name cannot be found.", "ネットワーク名が見つかりません。"),
        new("80", "ERROR_FILE_EXISTS", "The file exists.", "ファイルは既に存在します。"),
        new("82", "ERROR_CANNOT_MAKE", "The directory or file cannot be created.", "ディレクトリまたはファイルを作成できません。"),
        new("86", "ERROR_INVALID_PASSWORD", "The specified network password is not correct.", "指定されたネットワークパスワードが正しくありません。"),
        new("87", "ERROR_INVALID_PARAMETER", "The parameter is incorrect.", "パラメーターが間違っています。"),
        new("89", "ERROR_NO_PROC_SLOTS", "The system cannot start another process at this time.", "システムはこれ以上プロセスを開始できません。"),
        new("109", "ERROR_BROKEN_PIPE", "The pipe has been ended.", "パイプが閉じられました。"),
        new("110", "ERROR_OPEN_FAILED", "The system cannot open the device or file specified.", "指定されたデバイスまたはファイルを開けません。"),
        new("111", "ERROR_BUFFER_OVERFLOW", "The file name is too long.", "ファイル名が長すぎます。"),
        new("112", "ERROR_DISK_FULL", "There is not enough space on the disk.", "ディスクの空き容量が不足しています。"),
        new("120", "ERROR_CALL_NOT_IMPLEMENTED", "This function is not supported on this system.", "この関数はこのシステムではサポートされていません。"),
        new("121", "ERROR_SEM_TIMEOUT", "The semaphore timeout period has expired.", "セマフォのタイムアウト期間が終了しました。"),
        new("122", "ERROR_INSUFFICIENT_BUFFER", "The data area passed to a system call is too small.", "システムコールに渡されたデータ領域が小さすぎます。"),
        new("123", "ERROR_INVALID_NAME", "The filename, directory name, or volume label syntax is incorrect.", "ファイル名、ディレクトリ名、またはボリュームラベルの構文が正しくありません。"),
        new("126", "ERROR_MOD_NOT_FOUND", "The specified module could not be found.", "指定されたモジュールが見つかりませんでした。"),
        new("127", "ERROR_PROC_NOT_FOUND", "The specified procedure could not be found.", "指定されたプロシージャが見つかりませんでした。"),
        new("128", "ERROR_WAIT_NO_CHILDREN", "There are no child processes to wait for.", "待機する子プロセスがありません。"),
        new("131", "ERROR_NEGATIVE_SEEK", "An attempt was made to move the file pointer before the beginning of the file.", "ファイルの先頭より前にファイルポインタを移動しようとしました。"),
        new("145", "ERROR_DIR_NOT_EMPTY", "The directory is not empty.", "ディレクトリが空ではありません。"),
        new("161", "ERROR_BAD_PATHNAME", "The specified path is invalid.", "指定されたパス名が無効です。"),
        new("170", "ERROR_BUSY", "The requested resource is in use.", "要求されたリソースは使用中です。"),
        new("183", "ERROR_ALREADY_EXISTS", "Cannot create a file when that file already exists.", "そのファイルが既に存在するため作成できません。"),
        new("193", "ERROR_BAD_EXE_FORMAT", "%1 is not a valid Win32 application.", "%1は有効なWin32アプリケーションではありません。"),
        new("206", "ERROR_FILENAME_EXCED_RANGE", "The filename or extension is too long.", "ファイル名または拡張子が長すぎます。"),
        new("231", "ERROR_PIPE_BUSY", "All pipe instances are busy.", "すべてのパイプインスタンスが使用中です。"),
        new("232", "ERROR_NO_DATA", "The pipe is being closed.", "パイプが閉じられようとしています。"),
        new("234", "ERROR_MORE_DATA", "More data is available.", "使用可能なデータがまだあります。"),
        new("258", "WAIT_TIMEOUT", "The wait operation timed out.", "待機操作がタイムアウトしました。"),
        new("259", "ERROR_NO_MORE_ITEMS", "No more items are available.", "これ以上使用可能な項目はありません。"),
        new("267", "ERROR_DIRECTORY", "The directory name is invalid.", "ディレクトリ名が無効です。"),
        new("1053", "ERROR_SERVICE_REQUEST_TIMEOUT", "The service did not respond to the start or control request in a timely fashion.", "サービスが開始または制御要求に時間内に応答しませんでした。"),
        new("1058", "ERROR_SERVICE_DISABLED", "The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.", "サービスが無効になっているか、関連付けられた有効なデバイスがないため、開始できません。"),
        new("1060", "ERROR_SERVICE_DOES_NOT_EXIST", "The specified service does not exist as an installed service.", "指定されたサービスはインストールされたサービスとして存在しません。"),
        new("1062", "ERROR_SERVICE_NOT_ACTIVE", "The service has not been started.", "サービスが開始されていません。"),
        new("1223", "ERROR_CANCELLED", "The operation was canceled by the user.", "操作はユーザーによってキャンセルされました。"),
        new("1231", "ERROR_NETWORK_UNREACHABLE", "The network location cannot be reached.", "ネットワークの場所に到達できません。"),
        new("1232", "ERROR_HOST_UNREACHABLE", "The remote host cannot be reached.", "リモートホストに到達できません。"),
        new("1314", "ERROR_PRIVILEGE_NOT_HELD", "A required privilege is not held by the client.", "クライアントは必要な特権を保持していません。"),
        new("1326", "ERROR_LOGON_FAILURE", "Logon failure: unknown user name or bad password.", "ログオンに失敗しました:ユーザー名またはパスワードが正しくありません。"),
        new("1327", "ERROR_ACCOUNT_RESTRICTION", "Logon failure: account logon restriction.", "ログオンに失敗しました:アカウントのログオン制限です。"),
        new("1328", "ERROR_INVALID_LOGON_HOURS", "Logon failure: account logon time restriction violation.", "ログオンに失敗しました:許可されたログオン時間ではありません。"),
        new("1330", "ERROR_PASSWORD_EXPIRED", "Logon failure: the specified account password has expired.", "ログオンに失敗しました:パスワードの有効期限が切れています。"),
        new("1331", "ERROR_ACCOUNT_DISABLED", "Logon failure: account currently disabled.", "ログオンに失敗しました:アカウントが無効になっています。"),
        new("1332", "ERROR_NONE_MAPPED", "No mapping between account names and security IDs was done.", "アカウント名とセキュリティIDのマッピングが行われませんでした。"),
        new("1460", "ERROR_TIMEOUT", "This operation returned because the timeout period expired.", "タイムアウト期間が経過したため、この操作は終了しました。"),
        new("1722", "RPC_S_SERVER_UNAVAILABLE", "The RPC server is unavailable.", "RPCサーバーを利用できません。"),
        new("10004", "WSAEINTR", "A blocking operation was interrupted by a call to WSACancelBlockingCall.", "ブロッキング操作がWSACancelBlockingCallの呼び出しによって中断されました。"),
        new("10013", "WSAEACCES", "Permission denied.", "アクセス許可がありません。"),
        new("10014", "WSAEFAULT", "Bad address.", "不正なアドレスです。"),
        new("10022", "WSAEINVAL", "Invalid argument.", "無効な引数です。"),
        new("10024", "WSAEMFILE", "Too many open files.", "オープンしているファイルが多すぎます。"),
        new("10035", "WSAEWOULDBLOCK", "Resource temporarily unavailable.", "リソースが一時的に利用できません。"),
        new("10036", "WSAEINPROGRESS", "Operation now in progress.", "操作は現在進行中です。"),
        new("10038", "WSAENOTSOCK", "Socket operation on non-socket.", "ソケットでない記述子に対するソケット操作です。"),
        new("10048", "WSAEADDRINUSE", "Address already in use.", "アドレスは既に使用されています。"),
        new("10049", "WSAEADDRNOTAVAIL", "Cannot assign requested address.", "要求されたアドレスを割り当てられません。"),
        new("10050", "WSAENETDOWN", "Network is down.", "ネットワークがダウンしています。"),
        new("10051", "WSAENETUNREACH", "Network is unreachable.", "ネットワークに到達できません。"),
        new("10053", "WSAECONNABORTED", "Software caused connection abort.", "ソフトウェアが原因で接続が中断されました。"),
        new("10054", "WSAECONNRESET", "Connection reset by peer.", "リモートホストにより接続がリセットされました。"),
        new("10055", "WSAENOBUFS", "No buffer space available.", "使用可能なバッファ空間がありません。"),
        new("10057", "WSAENOTCONN", "Socket is not connected.", "ソケットが接続されていません。"),
        new("10060", "WSAETIMEDOUT", "Connection timed out.", "接続がタイムアウトしました。"),
        new("10061", "WSAECONNREFUSED", "Connection refused.", "接続が拒否されました。"),
        new("10065", "WSAEHOSTUNREACH", "No route to host.", "ホストへの経路がありません。"),
        new("11001", "WSAHOST_NOT_FOUND", "Host not found.", "ホストが見つかりません。"),
    };

    public static IReadOnlyList<ErrorCodeEntry> SmtpCodes { get; } = new List<ErrorCodeEntry>
    {
        new("211", null, "System status, or system help reply", "システムステータス、またはシステムヘルプの応答"),
        new("214", null, "Help message", "ヘルプメッセージ"),
        new("220", null, "<domain> Service ready", "<ドメイン> サービス準備完了"),
        new("221", null, "<domain> Service closing transmission channel", "<ドメイン> サービスが通信チャネルを閉じます"),
        new("250", null, "Requested mail action okay, completed", "要求されたメールアクションは正常に完了しました"),
        new("251", null, "User not local; will forward to <forward-path>", "ユーザーはローカルではありません。転送します"),
        new("252", null, "Cannot VRFY user, but will accept message and attempt delivery", "ユーザーをVRFYできませんが、メッセージを受け付けて配送を試みます"),
        new("354", null, "Start mail input; end with <CRLF>.<CRLF>", "メール本文の入力を開始してください。終端は<CRLF>.<CRLF>です"),
        new("421", null, "<domain> Service not available, closing transmission channel", "<ドメイン> サービスが利用できないため、通信チャネルを閉じます"),
        new("450", null, "Requested mail action not taken: mailbox unavailable", "要求されたメールアクションは実行されませんでした:メールボックスが利用できません"),
        new("451", null, "Requested action aborted: local error in processing", "要求されたアクションは中止されました:処理中のローカルエラー"),
        new("452", null, "Requested action not taken: insufficient system storage", "要求されたアクションは実行されませんでした:システムの記憶域が不足しています"),
        new("454", null, "TLS not available due to temporary reason", "一時的な理由によりTLSが利用できません"),
        new("455", null, "Server unable to accommodate parameters", "サーバーはパラメーターに対応できません"),
        new("500", null, "Syntax error, command unrecognized", "構文エラー、コマンドを認識できません"),
        new("501", null, "Syntax error in parameters or arguments", "パラメーターまたは引数に構文エラーがあります"),
        new("502", null, "Command not implemented", "コマンドが実装されていません"),
        new("503", null, "Bad sequence of commands", "コマンドの順序が不正です"),
        new("504", null, "Command parameter not implemented", "コマンドパラメーターが実装されていません"),
        new("530", null, "Authentication required", "認証が必要です"),
        new("535", null, "Authentication credentials invalid", "認証情報が無効です"),
        new("550", null, "Requested action not taken: mailbox unavailable", "要求されたアクションは実行されませんでした:メールボックスが利用できません"),
        new("551", null, "User not local; please try <forward-path>", "ユーザーはローカルではありません。転送先を試してください"),
        new("552", null, "Requested mail action aborted: exceeded storage allocation", "要求されたメールアクションは中止されました:割り当て容量を超過しました"),
        new("553", null, "Requested action not taken: mailbox name not allowed", "要求されたアクションは実行されませんでした:メールボックス名が許可されていません"),
        new("554", null, "Transaction failed", "トランザクションが失敗しました"),
    };

    /// <summary>コード、マクロ名、英語/日本語の説明文のいずれかに大文字小文字を無視して部分一致する項目に絞り込む。</summary>
    /// <param name="entries">検索対象エラーコード一覧</param>
    /// <param name="query">検索クエリ文字列</param>
    /// <returns>絞り込まれたエラーコード一覧</returns>
    public static IReadOnlyList<ErrorCodeEntry> Search(IReadOnlyList<ErrorCodeEntry> entries, string? query)
    {
        if (string.IsNullOrWhiteSpace(query))
        {
            return entries;
        }

        string trimmed = query.Trim();
        return entries.Where(entry =>
            entry.Code.Contains(trimmed, StringComparison.OrdinalIgnoreCase) ||
            (entry.MacroName is not null && entry.MacroName.Contains(trimmed, StringComparison.OrdinalIgnoreCase)) ||
            entry.DescriptionEn.Contains(trimmed, StringComparison.OrdinalIgnoreCase) ||
            entry.DescriptionJa.Contains(trimmed, StringComparison.OrdinalIgnoreCase)
        ).ToList();
    }

    /// <summary>クリップボードへのコピー用に、1件分のエラーコードを { Code, Macro, Description } のJSONへ整形する。</summary>
    /// <param name="entry">エラーコード情報</param>
    /// <param name="useJapaneseDescription">日本語説明を使用するフラグ</param>
    /// <returns>JSON形式の文字列</returns>
    public static string ToJson(ErrorCodeEntry entry, bool useJapaneseDescription)
    {
        string description = useJapaneseDescription ? entry.DescriptionJa : entry.DescriptionEn;
        return JsonSerializer.Serialize(new { entry.Code, Macro = entry.MacroName, Description = description }, JsonOptions);
    }
}
